import { useSession } from 'next-auth/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { data, status } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Landing Page</h1>

      <h1>Hi {data ? data.user.name : 'Admin'}</h1>
    </div>
  )
}
